// Activity versions — source of truth for which build of each sandbox
// activity is currently live. Used by:
//   - DemoSandboxPage (visible badge so testers know what they're poking at)
//   - FeedbackButton  (included in the submit-feedback payload so admin
//                      triage can tell which version a comment refers to)
//   - AdminFeedbackPage (shown in the expanded row + CSV export)
//
// Versioning convention
// ---------------------
// vMAJOR.MINOR
//   - Bump MINOR for copy / wording / styling / small UX tweaks.
//   - Bump MAJOR for structural changes to the flow, scoring, or data shape.
// Always update `updated` to today and prepend a one-line note to
// `changelog` when bumping. Older notes stay so the history is readable
// without git archaeology.
//
// When you change an activity component, BUMP THE VERSION in the same
// commit. Future-Josh / future-Claude relies on this being accurate.

export const ACTIVITY_VERSIONS = {
  assent: {
    version: 'v1.4',
    updated: '2026-08-24',
    changelog: [
      '2026-08-24 · v1.4 — Draft 96 (MINOR — additive UI, no data-shape change). New 988 Suicide & Crisis Lifeline callout (Dr. Sprang\'s ask, 2026-08-24 team meeting) between the body text and the Yes/No decision box — its own visible amber-toned card (`CrisisLifelineNote`, shared with the Plan keepsake and the end-of-program celebration screen), not folded into paragraph text. Draft copy, reviewable. Save payload unchanged ({ assent: "yes" | "no" }).',
      '2026-08-19 · v1.3 — Draft 92 (MINOR — additive UI, no data-shape change). New optional "🔊 Read this to me" narration: a collapsed pill above the title block reveals a native audio player (Josh\'s recorded narration of the assent document) on click — no autoplay on mount, no gating of the Yes/No decision (unlike KaiNarrationPlayer elsewhere, there is no Continue button here to gate). Fails open on a missing/broken file: a plain "not available yet" message replaces the player rather than a dead control. Save payload unchanged ({ assent: "yes" | "no" }).',
      '2026-07-22 · v1.2 — per Josh, dropped the "AGE 11" qualifier from the assent title line ("ASSENT TO PARTICIPATE IN A RESEARCH STUDY FOR CHILDREN AGE 11" → "…FOR CHILDREN"). Component + live intervention updated; live republished as version 5. No other copy change.',
      '2026-07-22 · v1.1 — title + copy corrected to be VERBATIM from the assent doc (verified programmatically against the source paragraphs). Title is now the doc\'s exact 4-line block ("A SINGLE SESSION PROGRAM TO FOSTER BELONGINGNESS" / "ASSENT TO PARTICIPATE IN A RESEARCH STUDY FOR CHILDREN AGE 11" / "UNIVERSITY OF KENTUCKY" / "CENTER ON TRAUMA AND CHILDREN") instead of the earlier friendly heading. Decision line fixed to the doc wording (lowercase "yes", "No" with the period outside the quote); Yes/No buttons relabeled to the doc\'s plain "Yes" / "No". Body already matched word-for-word (only invisible non-breaking-space / trailing-whitespace artifacts normalized). Live intervention republished as version 4 with the same corrected copy.',
      '2026-07-22 · v1.0 — initial build of the Child Assent screen, the first thing a participant sees (before the pretest). Copy from the IRB assent document (Belongingness_Assent_ages 6-11_updated7.22.26.doc). Reads the assent, then a Yes/No decision: Yes advances into the program; No ends on a friendly exit screen. Authored into the live "Ready! Set! Dedicate!" intervention as its new first section (a text_prompt + a Yes/No choice item whose exit_on ends the session on "no"); this sandbox component mirrors that flow. Save payload { assent: "yes" | "no" }.',
    ],
  },
  'getting-unstuck': {
    version: 'v5.11',
    updated: '2026-08-27',
    changelog: [
      '2026-08-27 · v5.11 — Draft 100 (MINOR — additive UX, no data-shape change). Continue no longer just sits disabled across any of this activity\'s 5 gates (rate every thought, the Other-thought Yes/No + text + rating, pick 2 thoughts, finish the Kai narration, pick-a-strategy + fill in the response) — it stays tappable, and tapping it while incomplete names what\'s missing. The rate/other/strategy gates name the specific missing item and scroll to/highlight it; the pick gate (a count, not a specific item) and the narration gate (nothing to point at) get a plain message instead. Save payload unchanged.',
      '2026-08-26 · v5.10 — real bug fix (Josh, staged live-preview review; MINOR — no save-payload shape change). The "pick" screen\'s heading says "Pick the top two thoughts," but Continue only ever required at least 1 selected, so a participant could proceed after picking just one. Now requires exactly `min(MAX_PICKS, eligibleItems.length)` — 2 in the normal case, or the most actually achievable if only 1 thought cleared the eligibility threshold (so a legitimately 1-eligible-item session still isn\'t locked out).',
      '2026-08-11 · v5.9 — Draft 62 Parts A/B/C (2026-08-11 meeting). (A) 0-endorsement fallback: previously, rating nothing ≥2 dropped the kid into a static "affirmation" dead-end (two-strategies explainer, straight to Save, no actual practice) — Holly flagged that this let a kid skip Challenge/Both-And entirely. Now the kid sees Stephanie\'s copy ("Try out the following exercise…") then practices on 2 RANDOMLY-selected thoughts from the locked 6-item pool (a_other excluded from the random pool), same Challenge/Both-And UI as endorsed picks. New `zero_endorsement_intro` phase; the 2 auto-picked items get `selected: true, randomly_selected: true` in state, surfaced in the save payload as `randomly_selected: true` on those two appraisal entries (absent/false otherwise) so export can tell endorsed apart from randomly-given. (B/C) New shared `KaiNarrationPlayer` component (audio + always-visible transcript, autoplay with a Play-button fallback, Continue-gating `onComplete`) replaces the old affirmation screen\'s "Video Coming Soon" placeholder — surfaced via a new `kai_strategy_intro` gate shown once before the FIRST strategy screen on EITHER path (normal pick or the fallback), since "the two-strategies work" is the same single code path for both. Audio file (`getting-unstuck-strategies-intro.mp3`) does not exist yet — Josh drops it at `public/kai-narration/` after this ships; until then the KaiNarrationPlayer has nothing to autoplay, which is expected.',
      '2026-06-29 · v5.8 — Draft 36 Part D (MAJOR — appraisals data-shape grows). Challenge final prompt reworded from "What comes up for you when you ask yourself those questions?" to "Now that you\'ve thought about your statement in different ways, what is a more helpful or more accurate statement you could tell yourself?" (Adrienne — push for an alternative statement, not journaling). Both/And path now seeds from a new per-appraisal `both_and_root` field (a softened/conditional version of the absolute original, e.g. "I will never really feel like I belong" → "I don\'t feel like I belong right now") so the kid can coherently AND-extend it — resolving the mismatch where the I-need-help Both/And suggestions already used a softened root but the input UI used the absolute statement (Holly + Jessica + Stephanie). The Both/And review line uses the same root. `both_and_root` is intervention-side only; the original `text` is unchanged and still drives the Pick rating, the Challenge path, and the pretest / FollowUp Survey measures. Save payload unchanged. a_other (the kid\'s custom thought) has no root and falls back to its text.',
      '2026-06-18 · v5.7 — Draft 32 Part D. Dropped the "Need an example?" disclosure on the Both/And screens per Stephanie\'s 2026-06-18 "pick one" feedback (Josh resolved in favor of keeping "I need help"); the strategy-aware help panel (Draft 27) is now the single help affordance. Renamed the button "I need help" → "I need help creating a new thought" (Holly — so kids don\'t read it as tech support). Restyled it bigger + bolder (Jessica + Holly) as a secondary CTA (amber-100 pill, amber-300 border, text-[15px] font-semibold) rather than a subtle text link. Confirmed it appears on both Challenge and Both/And strategy screens. Removed the now-unused `BOTH_AND_EXAMPLES` constant. No data-shape or export change.',
      '2026-06-12 · v5.6 — Updated "I need help" alternative thoughts to v2 source doc (Holly\'s a5 Challenge edit "even just a little bit, and trust can grow" — Stephanie agreed — plus minor punctuation alignment on a4 Both/And and a5 Challenge). Content-only swap in `src/lib/appraisals.js`; no data-shape, UI, or export change.',
      '2026-06-09 · v5.5 — Draft 27 (MINOR). Replaced the placeholder "I need help" alternative-thought content with Stephanie\'s real content (Alternative Thoughts list, 2026-06-09). Restructured `help_suggestions` in `src/lib/appraisals.js` from a flat array to a strategy-keyed object (`{ challenge: [...], both_and: [...] }`, two per strategy per item, 24 total) so the help panel surfaces Challenge-vs-Both/And-appropriate alternatives based on the kid\'s currently-selected strategy; panel read-path updated to `help_suggestions[currentStrategy]` (defaults to challenge). No save-payload or export change.',
      '2026-06-08 · v5.4 — Draft 26 (MAJOR — scale change). Truth-rating scale shifted from 0-5 (6 points) to 0-4 (5 points): anchors now 0 Not At All True / 2 Somewhat True / 4 Definitely True (2 is exactly the middle). The shared `src/lib/appraisals.js` scale drives both this activity and the FollowUp Survey, so the change applies to both at once (FollowUp v1.1). Pick eligibility threshold stays at ≥2 ("Somewhat True" or above). Added an "I need help" button on each thought-work screen that opens a panel of alternative-thought suggestions for that appraisal item — tapping one pre-fills the response field as a starting point; PLACEHOLDER content for now (Stephanie producing the real lists; swap in a follow-up commit, no UI change). Save payload shape unchanged except `truth_rating` range narrows 0..5 → 0..4; exportFlatten value-range comments + demoDataset regen updated. Breaking value-range change; no real participant data exists yet.',
      '2026-06-01 · v5.3 — Draft 20. Two changes. (1) Pick-screen eligibility threshold reverted to ≥2 (was ≥3 since v5.1) — FINAL per the 2026-06-01 meeting; a kid who rates an item at 2 (above the 0 "Not At All True" floor) is endorsing it enough to be worth offering the Pick / Challenge / Both-and flow. This is the third 3↔2 flip on this constant; the flip history is recorded in the ELIGIBILITY_THRESHOLD comment so future-us doesn\'t reopen it casually. Affirmation path is hit less often as a result. (2) Added a brief affirmation beat between consecutive picked thoughts (new `cycle_affirmation` phase): when a kid finishes one thought and has another queued, they see a short randomized "Nice work / Good job / You\'re doing this / Keep going" screen + "Let\'s try the next one" before the next strategy screen (Ginny\'s 2026-06-01 encouragement ask). Also surfaced a Challenge-vs-Both/And strategy explainer (video placeholder + text scaffolding) on the affirmation path so kids who don\'t pick a thought still learn the two strategies. No data-shape change.',
      '2026-05-19 · v5.2 — Pick-screen prompt reworded to "Pick the top two thoughts you would like to work on" (Holly\'s 2026-05-18 transcript suggestion). Replaces the previous "Which of these thoughts… Pick one or two." pairing — max-2 guidance is now in the prompt itself rather than as a footnote. No data-shape change; the max-2 cap behavior, the eligible-thoughts filter, and the non-blocking nudge on a third tap all stay as v5.0 implemented them.',
      '2026-05-19 · v5.1 — Reverted Pick-screen eligibility threshold from ≥2 back to ≥3 (Josh, 2026-05-18 — clinical-content call overriding the v5.0 lowering). Items rated below "Somewhat True" on the 0-5 anchor scale aren\'t endorsed strongly enough to be worth the Pick / Challenge / Both-and flow. Affirmation path will be hit more often as a result — intended behavior. No data-shape change.',
      '2026-05-13 · v5.0 — Draft 15 rebuild. Replaced the 8 stuck thoughts with the 6 locked Appraisal items from the FollowUp Survey (single source in `src/lib/appraisals.js` — same items, same wording, same scale used in both intervention + survey so within-subject change scores are valid). Dropped "how often" rating; only "how true" remains on a 0-5 scale with Not At All / Somewhat / Definitely True anchors. Pick threshold lowered to ≥2 (Stephanie: items rated above 1 weren\'t being pulled forward). Added an "Other thought" addendum screen — Yes/No, optional free text + same 0-5 rating, eligible for Pick if rated ≥2. Fight → Challenge rename finalized after three flips: button "Challenge it", data key `strategy: "challenge"`, response field `response` (renamed from `fight_response`/`challenge_response`). Jessica\'s 2026-05-18 copy edit: response prompt ends "those questions?" not "those?". Save payload reshaped: `appraisals` is now a dict keyed by id (`a1`–`a6` + optional `a_other`) with per-item `truth_rating` / `selected` / `strategy?` / `response?` / `and_statement?` / `text?`. exportFlatten emits per-item columns `unstuck_truth_a1..a6`, `_selected_a*`, `_strategy_a*`, `_response_a*`, plus the same set for `a_other` and rollup counts `unstuck_n_challenge` / `unstuck_n_both_and`. The v4 columns `unstuck_freq_st*`, `unstuck_belief_st*`, `unstuck_*_st*`, `unstuck_n_fight`, `unstuck_thought_ids` are gone. demoDataset regenerated. Breaking change; no real participant data exists yet.',
      '2026-05-12 · v4.0 — reverted the "Fight it" → "Challenge it" rename from v2.0. Strategy label back to "Fight it", strategy data key back to `fight`, response field back to `fight_response`. Stephanie\'s original clinical-content call (use "challenge" as more clinically standard) was overridden by Josh; the original RSD framing of "Fight it" is restored throughout — UI labels, data keys, export columns (`unstuck_n_fight`, allowed_values `fight | both_and`), and synthetic-demo dataset. Everything else from v3.0 (rate/pick split, max-2 thought selection, affirmation path for no-eligible) stays. Save payload data-shape change — analyst-side a downstream consumer expecting v2.0/v3.0 `challenge` keys would need updating, but no real participant data exists yet.',
      '2026-05-12 · v3.0 — separated rating and selection into two distinct screens. Rate screen now shows all 8 thoughts with the 5-point scales only; the per-thought "I want to work on this" button is gone. New Pick screen filters to thoughts rated ≥3 on either scale and shows them as selectable cards with a max-2 selection limit (non-blocking "Pick up to 2" nudge on third tap). New affirmation path: if no thought clears the eligibility threshold, Pick is skipped and a short "That\'s good news" screen leads straight to Save. Data shape unchanged — only the path to becoming selected changed.',
      '2026-05-11 · v2.0 — replaced the Kai-quote intro (Ginny: confusing) with a per-thought 5-point appraisal scale (frequency + believability). Eligibility threshold: rated ≥3 on either scale unlocks the "I want to work on this" button. "Fight it" renamed to "Challenge it" throughout (Stephanie — more clinically standard), including data keys (`fight` → `challenge`, `fight_response` → `challenge_response`). Restored the three challenge prompts as scaffolding above a single open-ended response field (Stephanie\'s PPT slide 12). Both/And unchanged. Save payload gains an `appraisals` array covering all 8 thoughts. Breaking change to data shape, demo-only.',
      '2026-05-11 · v1.0 — initial demo release.',
    ],
  },
  'allies-safety-net': {
    version: 'v6.0',
    updated: '2026-08-16',
    changelog: [
      '2026-08-16 · v6.0 — Draft 88 Part B (MAJOR — a whole mid-flow screen is removed). The post-save confirmation\'s "Save as image" button (and its download plumbing) is removed; the confirmation keeps the net visual + strengthen summary. Nothing may invite the participant out of the app before the posttest: the program\'s only download actions now live on the post-posttest completion screen (DeliveryShellPage), which renders the consolidated Plan keepsake from the saved payloads. Response payload unchanged. (In the live flow the removed screen was never actually reached — the engine advances as soon as onSave resolves — so this mainly aligns the sandbox with the live experience.)',
      '2026-08-13 · v5.9 — Draft 65 (2026-08-13, now that the Kai narration audio has landed). (A) `KaiNarrationPlayer` gains a small circular Kai portrait next to the speaker icon so the participant sees who\'s talking — shared-component change, both narration spots on this activity pick it up automatically. (B) Removed body copy on the intro and Inspect-education screens that duplicated Kai\'s narration transcript almost verbatim: the intro screen\'s opening ally-definition sentence ("An ally is someone you trust to provide support...") and closing "Let\'s build your safety net." line are gone — the additive second sentence ("They might not always get it right...") and the three color-coded support-type bullets stay; the Inspect-education screen\'s four red-flag bullets below the player are gone (the same four warning signs are already verbatim in the transcript) — the intro paragraph above the player and the closing "On the next screen..." paragraph stay. (C) The intro transcript\'s "practical support" / "emotional support" / "social support" now render in the same amber/rose/sky tones as the `SUPPORT_TYPES` bullets below, for visual consistency from first mention. Display-only; no data-shape change.',
      '2026-08-11 · v5.8 — Draft 62 Part B (2026-08-11 meeting). Two spots gain Kai audio narration via the new shared `KaiNarrationPlayer` component (autoplay + always-visible transcript + Continue-gated on `onComplete`): the intro screen (before ally selection) and the Inspect-education screen (before Inspect X-out), where it replaces the old "Video Coming Soon" placeholder. Continue on both screens is disabled until that screen\'s narration has played once (sticky — a later replay doesn\'t re-lock it). Existing static text on both screens is unchanged; the narration is additive. Audio files (`safety-net-allies-intro.mp3`, `safety-net-inspect-intro.mp3`) do not exist yet — Josh drops them at `public/kai-narration/` after this ships; until then the KaiNarrationPlayer has nothing to autoplay, which is expected. No data-shape change.',
      '2026-08-03 · v5.7 — Draft 58 Part B (2026-08-03 meeting; Bianca got stuck on Step 10). Bug fix: on the Inspect X-out screen, the × removal badge is now its OWN clickable/focusable control (in `TrampolineNet.jsx`) with a generously padded invisible hit circle — previously the badge visual had `pointer-events: none` and sat outside the halo\'s hit-tested radius, so tapping directly on it did nothing; the whole ally icon/halo was the (accidental) real click target instead, which read as an unreliable X. Clicking the person icon/halo no longer removes an ally — only the × (or restore icon) does, with room for imprecise taps around it. No visual change to the badge or icon; no data-shape change.',
      '2026-06-29 · v5.6 — Draft 36 Part E. Support-type percentage labels removed entirely from every surface (TrampolineNet pills + ally-list headers) per the 2026-06-29 meeting consensus — they were misleading (one ally per type read as "100% supported"). The `percentByType`/`showPercentages` props remain on TrampolineNet (default off) but are no longer passed; this also fixes the mobile "Social" label clipping. Bolded + warm-colored the small-net caption ("A small net is a place to start — let\'s keep building") so it reads as encouragement, not faint body text (Adrienne + Holly). Dropped the second "Lots of room to grow … greyed-out areas" caption line that confused kids without empty wedges (Holly). The Draft 32 "No one named for: {types}" callout is unchanged. No data-shape change.',
      '2026-06-18 · v5.5 — Draft 32 Part E. (1) Strengthen per-type "e.g." examples rewritten so each matches its support type (Holly: "hang out on weekends" is social, not practical) — Practical "takes me to practice", Emotional "someone to talk to when I am feeling down", Social unchanged. (2) Post-save reveal copy softened "Some allies show up in more than one place" → "Some allies may show up…" so it doesn\'t read as wrong for kids without multi-placed allies (Holly). (3) Empty-wedge gap prominence (Stephanie): the "No {type} yet" pills are bigger + near-solid (was small + faded), and an explicit "No one named for: {types}" callout (per-type color-coded) renders below the net whenever any support type has zero allies — at all ally counts, not just the ≤2 equal-thirds case. Display-only; no data-shape/export/save change.',
      '2026-06-12 · v5.4 — Draft 30, two fixes from Josh\'s 2026-06-12 walkthrough. (1) Support-type percentage labels are gated to post-selection surfaces only — they no longer appear on the three transition screens or the per-type selection question (where they shifted in real time as the kid picked, reading e.g. "Practical 100% / Emotional 0%" before the kid had even been asked about Emotional). Percentages still show on the post-selection net reveal, Inspect, Review, and saved confirmation (TrampolineNet pills + ally-list headers). (2) Low-ally geometry: when total allies ≤ 2, the net now uses equal 120° thirds instead of proportional wedges, so a single ally no longer expands to ~330° and reads as "this area is full"; the filled wedge keeps its pattern + icon, empty wedges keep their greyed fill + "No X yet" pill (which now have room not to overlap). New `equalThirds` prop on TrampolineNet, driven by the same ≤2 threshold as the existing 60%-opacity demotion. Added a second caption line under "A small net is a place to start": "Lots of room to grow your safety net in the greyed-out areas." Both fixes are display-only — no data-shape, export, or save-payload change.',
      '2026-06-08 · v5.3 — Draft 26 (NOTE: the draft labeled this "v5.1 → v5.2", but Draft 23 had already shipped v5.2, so this lands as v5.3). Adrienne\'s Round 4 feedback: (1) "!" added to the affirmation line ("Your safety net is ready!"). (2) Percentage labels appended to each support-type heading throughout — transition screens, per-type selection-screen question, the TrampolineNet label pills (so Inspect + Review show them), and the textual ally-list section headers. Percent = allies-in-type ÷ total distinct allies (a multi-type ally counts toward each type\'s numerator, so percents can sum >100%); rendered only when total allies > 0. (3) Visual demotion of the full net when total allies ≤ 2: the net dims to 60% opacity and a slate-600 caption ("A small net is a place to start — let\'s keep building.") appears, on the full-net screens (build-final, Inspect X-out, Review, saved confirmation). Per-type selection screens unaffected. New `percentByType` prop on TrampolineNet for the pill labels. No data-shape or export change.',
      '2026-06-04 · v5.2 — Draft 23. Each Strengthen screen now shows the kid which allies they already selected for that support type (post-Inspect, so removed allies are excluded) as a read-only refresher line above the "Is there anyone else…" prompt — singular/plural-aware, Oxford-comma list, skipped entirely when none. Helps the kid generate a genuinely new addition rather than restating someone already named. Display-only; no flow, data-shape, or export change.',
      '2026-06-01 · v5.1 — Draft 20, two Strengthen-step changes from Ginny\'s 2026-06-01 stress test. (1) Strengthen now runs for ALL three support types, not just gaps (0/1 ally) — even a kid with plenty of allies in a type might think of someone else worth adding when prompted, and the gap-only gate missed that. (2) Removed the same-kid suggestion chips: when a kid had selected the same people (e.g. foster mom/dad) across every type, the chips re-suggested them and the net never actually expanded. The kid now types a name from scratch. Copy reframed from gap-specific sub-lines ("nobody is in your X support") to a single neutral "Is there anyone else who could give you {type} support? Adding more people can make your safety net stronger." Typed-in names live in the action callouts only — they are NOT added to the net visual (Stephanie: an aspirational name "isn\'t really in the net until we call him and see"). Data shape: `strengthened.{type}` is now always populated (never null); `gap_filler` field renamed to `additional_person`. exportFlatten drops `safety_net_strengthen_gaps_count`, adds `safety_net_strengthen_added_count` (0-3), renames the per-type `_filler` columns to `_person`. demoDataset regenerated (~50% fill an additional person per type). No breaking JSON-level change beyond the field rename; demo-only.',
      '2026-05-19 · v5.0 — 22-tile icon set replaces v4.x\'s 15-tile set (foster → foster-mom + foster-dad; bio → bio-mom + bio-dad; grandparent → grandmother + grandfather; friend → friend + best-friend + friends; boyfriend, girlfriend added; sneaky-link deliberately not registered per Josh\'s 2026-05-19 call). Color-coded support types (Practical = amber, Emotional = rose, Social = sky) with brief transition screens between each Practical → Emotional → Social selection. Inspect (Part 2) restructured per Stephanie\'s 2026-05-18 transcript: educational screen with video placeholder + the four red-flag bullets (verbatim from her PPT) → single X-out-on-net screen where the kid taps × on any ally to take them out. The per-ally modal walkthrough with Yes/No/Not-sure questions is gone. Strengthen (Part 3) rebuilt from scratch (last torn down in v2.0): gap detection on post-removal counts (0 or 1 ally = gap); per-gap screen with same-kid ally chips as suggestion shortcuts, "Who could that be?" filler input, "What\'s one thing you could do?" action textarea, and a Skip option. Save payload reshaped: per-ally `inspected` / `flags` / `kept_in_net` replaced with a top-level `removed_via_inspect` array; new top-level `strengthened` object keyed by type. exportFlatten drops per-flag columns and adds `safety_net_strengthen_{type}_{filler|action|skipped}` + `_gaps_count`. demoDataset regenerated. Breaking data-shape change, demo-only.',
      '2026-05-12 · v4.1 — reverted inspect-modal question wording to Stephanie\'s PPT originals (Slide 4 "Is there anyone in your net that:" bullets). Q1: "usually get you into trouble" (was "sometimes get you in trouble"). Q2: "talking to or getting close to other people" (was the longer "spending time with other people who care about you" qualifier). Q4: "Do you feel afraid of {name}?" with the perspective flip (was "Does {name} sometimes make you feel afraid?"). Q3 unchanged. The v3.0 wording was my judgment call about kid-friendliness for content Stephanie wrote — not driven by team feedback. Josh decided 2026-05-12 to restore the PPT phrasing as written. Flag keys (`trouble`, `isolate`, `lies`, `afraid`) and Yes/No/Not sure answers are unchanged — no data-shape change.',
      '2026-05-12 · v4.0 — four coupled changes: (1) Desktop-bigger TrampolineNet — every render site now uses a responsive `max-w-[420px] md:max-w-[700px]` wrapper, and the SVG fills 100% of that container instead of being fixed at 400px. (2) New "Show me a list of my allies instead" toggle below every net render, expanding an inline grouped-by-type ally list (with kept/removed status indicators on post-inspect contexts). (3) Inspect flow restructured into a linear walkthrough: net stays as a backdrop with the current ally highlighted (new `highlightedAllyId` prop on TrampolineNet); the inspect modal auto-opens for each ally in sequence and auto-advances on Keep/Remove. Back button in modals walks to the previous ally; X-closing drops to a fallback view with Resume/Skip buttons. The old "Done inspecting" button is gone. (4) Visual refresh to match the new cleaner reference SVG — dropped the 24 radial cord lines, 4 concentric ring guides, thick wedge dividers, and the dot circles inside the woven patterns. Proportional wedge sizing by ally count is retained. Save payload UNCHANGED (still v3-shape with added version bump to "4.0").',
      '2026-05-12 · v3.1 — post-save confirmation now shows the TrampolineNet visual + a "Save as image" button that exports a PNG of the kid\'s safety net (rasterized client-side from the inline SVG; ally icon hrefs inlined as data URLs first to avoid canvas-tainting issues). No data-shape change.',
      '2026-05-11 · v3.0 — Inspect step added. Step 1\'s placeholder final visual replaced with the real TrampolineNet component (see src/components/TrampolineNet.jsx) — parametric SVG matching the Claude Design reference (3 nested rims, woven type patterns, 24 cord lines, 4 ring guides, label pills, "YOU" hub). Step 2 (Inspect) is a new 3-screen flow inside the same activity: intro → interactive net (tap any ally to inspect) → final net. Per-ally inspect modal asks 4 clinical-safety questions (trouble / isolate / lies / afraid). Keep + Remove buttons stay equally weighted; subtle amber border on cards with a "yes" answer, no destructive red on Remove. Keep-with-yes triggers a keep-advisory modal; remove triggers a removal-acknowledgment modal. Save fires at the end of Step 2 (not Step 1 anymore). All 15 ally SVGs had their background <rect> stripped so they composite cleanly on the net wedges. Save payload extends v2.0: per-ally `inspected`, `flags`, `kept_in_net`; activity-level `inspection_completed` flag.',
      '2026-05-11 · v2.0 — full rewrite. Old 4-step flow (Build → Inspect → Strengthen → Review) replaced with Variant C: per-support-type multi-select grid across 5 paginated screens (intro + Practical + Emotional + Social + Safety Net visual). 15 new SVG ally tiles (foster, bio, sibling, grandparent, otherfam, counselor, teacher, coach, babysitter, neighbor, friend, therapist, caseworker, other1, other2) with two custom-name slots. Per-screen "None of these" affirmative button captures meaningful "no one for this type" responses. Final screen is a placeholder grouped-by-type visual — final net+pie visual is a separate follow-up. Save payload reshaped: deduplicated allies list with support_types arrays + none_for flags. Steps 2–4 of the legacy activity removed; will be rebuilt as Task #7 after team design discussion.',
      '2026-05-11 · v1.0 — initial demo release (drag-id parsing fix already folded in).',
    ],
  },
  'self-reflection': {
    version: 'v1.7',
    updated: '2026-08-27',
    changelog: [
      '2026-08-27 · v1.7 — Draft 100 (MINOR — additive UX, no data-shape change). Next/Save no longer just sits disabled when the current screen\'s field(s) are empty — it stays tappable, and tapping it while incomplete names which field is missing (Thoughts / Feelings on the two-column screens, "your response" on the single-field memory screens) and scrolls to/highlights it. Save payload unchanged.',
      '2026-07-27 · v1.6 — Draft 55 Part B (2026-07-27 meeting; Bianca). Self-Reflection intentionally has no full end summary (it\'s processing, not skill-teaching), so the closing insight line ("Our experiences can drive our thoughts and feelings about belonging.") is promoted to the visual anchor of the closing screen (bigger + bold, navy); "Thanks for sharing!" softened to a warm follow-on. Typography only — no new content, no data-shape change.',
      '2026-06-29 · v1.5 — Draft 36 Part A. Closing reworked (Adrienne + Holly: bare "Thanks for sharing" read abrupt / slightly sarcastic) → a context line "Our experiences can drive our thoughts and feelings about belonging." + "Thanks for sharing!" (the "!" is intentional warmth). No data-shape change.',
      '2026-06-18 · v1.4 — Draft 32 Part A. Deleted the "Hold onto what came up" closing message (Ginny + Holly flagged it as unclear / no direction — same call as Draft 26\'s "we\'ll come back to it" removal); no replacement copy. Moved the example thought/feeling text out of the textarea `placeholder` into persistent slate-500 italic help text above each field, so it stays visible while the kid types (Holly). Wording unchanged from v1.3. No data-shape change.',
      '2026-06-08 · v1.3 — Draft 26. Removed the closing "we\'ll come back to it" line (Holly — there\'s no later activity that revisits the reflections); the simple Save confirmation stays. Added example thought/feeling placeholder text on the thoughts/feelings fields (Ginny — the fields read as ambiguous): inclusion → "e.g., People like me" / "e.g., Happy"; exclusion → "e.g., Nobody likes me" / "e.g., I felt sad". No data-shape change.',
      '2026-05-12 · v1.2 — reverted the v1.1 exclusion-prompt reframe back to the original wording ("Now think of a time you felt excluded — a time you felt like you did not belong"). The agentive reframe didn\'t go past Ginny\'s UX review and shipped early; Holly\'s proposal is moved to team-level design discussion.',
      '2026-05-11 · v1.1 — exclusion prompt reframed as agentive ("someone made you feel like you did not belong") per Holly\'s 2026-05-11 feedback.',
      '2026-05-11 · v1.0 — initial demo release.',
    ],
  },
  'belonging-skills-sort': {
    version: 'v4.1',
    updated: '2026-08-27',
    changelog: [
      '2026-08-27 · v4.1 — Draft 100 (MINOR — additive UX, no data-shape change). Continue no longer just sits disabled when nothing\'s sorted yet — it stays tappable, and tapping it while nothing\'s placed shows "Sort at least one skill before continuing." This gate is a count precondition (any one skill in any bucket clears it), not a per-item list, so there\'s no single missing item to scroll to or highlight. Save payload unchanged.',
      '2026-08-16 · v4.0 — Draft 88 Part B (MAJOR — a whole mid-flow screen is removed). The post-submit snapshot screen\'s "Save as image" button is removed; the three-bucket SVG snapshot itself stays. Nothing may invite the participant out of the app before the posttest: the program\'s only download actions now live on the post-posttest completion screen (DeliveryShellPage), which renders the consolidated Plan keepsake from the saved payloads. Response payload unchanged. (In the live flow the removed screen was never actually reached — the engine advances as soon as onSave resolves — so this mainly aligns the sandbox with the live experience.)',
      '2026-08-14 · v3.6 — Draft 70 (MINOR — interaction addition; fixes QA_MOBILE_2026-08 P0-2, where the "What I\'m already doing" bucket was unreachable by finger drag at phone height). (A) Tap-to-place: tapping a source card (a pointer sequence that moves < 8px) opens a bottom-sheet chooser — three bucket buttons + Cancel, one-thumb reachable regardless of where the card sits; choosing places the card exactly as a drag-drop would (same placeIntoBucket path, same stem-only bucket rendering, same payload). Tapping a placed card offers move-to-another-bucket / put-back-in-the-list via the same sheet (its ? and × buttons still work independently). Chooser buttons are real keyboard-operable <button>s; Escape/backdrop cancels; drag-and-drop is fully preserved alongside. (B) Drag edge auto-scroll: while a drag is active and the pointer is within 70px of the viewport top/bottom, a rAF loop scrolls the page 14px/frame and re-hit-tests the hovered bucket (the page moving under a stationary finger changes what\'s beneath it). Directions copy updated to lead with tap ("Tap each skill below to choose its bucket — or drag it in."). No data-shape change.',
      '2026-08-03 · v3.5 — Draft 58 Part A (2026-08-03 meeting; Bianca). Draft 55\'s bold `stem` prefix fixed the crowding on the sort page itself, but the buckets still rendered the FULL sentence once a card was dropped in. Buckets now show ONLY the bold stem — the source pile of cards (before dragging) and the end-of-activity summary/PNG both still show stem + full sentence, unchanged. Presentation only — no data-shape change.',
      '2026-07-27 · v3.4 — Draft 55 Part A (2026-07-27 meeting; Bianca crowding note). Each of the 7 behaviors gains a short bold `stem` label; the sort-page cards now lead with the bold stem then the rest of the sentence, so the buckets read as chunky labels instead of a wall of sentences. The drag ghost-chip uses the stem too. Full sentences still show on the cards and in the end-of-activity summary/PNG. Presentation only — no data-shape change.',
      '2026-06-29 · v3.3 — Draft 36 Part C. Directions copy now points the kid at the skill list below the buckets (Adrienne): "Drag each skill into a bucket" → "From the list of skills below, drag each one into a bucket." No data-shape change.',
      '2026-06-18 · v3.2 — Draft 32 Part C. Snapshot-screen closing message rewritten from the passive "Here\'s where you landed. It\'s yours to keep." to the action-oriented "Think about when you could try out one of these skills." (Holly). The action-plan pull-forward Josh flagged is deferred to the flow-integration draft (no false callback before the integration exists). No data-shape change.',
      '2026-06-08 · v3.1 — Draft 26. (1) Encouragement gains a "!" ("Nice work!"). (2) The post-submit screen renders a saveable PNG snapshot of the three sorted buckets (skill names inside each; unsorted excluded) via downloadSvgElementAsPng, same pattern as Allies / Safety Net + Who I Am Poem. (3) One-time "reconsider unsorted items?" prompt after the first Save click when skills remain unplaced — Yes returns to the sort UI, No saves; asked at most once. Data shape unchanged (the reconsider step just gives one more chance to move items from `unplaced` before save).',
      '2026-05-13 · v3.0 — five converging pieces of feedback from the 2026-05-18 review meeting. (1) The two CSS drop-zones replaced with three illustrated trapezoidal bucket SVGs (single shared `BucketSvg` component). (2) New third bucket "Not interested right now" — equal styling, no greying/desaturation per Stephanie\'s call. (3) Placement rebuilt as real drag with a ghost-chip follower using pointer events (not @dnd-kit, not HTML5 drag) — uniform across mouse, touch, pen. Ghost chip offsets above the finger on touch so it stays visible; settles into the bucket on drop with a ~240ms ease-out transition + bucket pulse. (4) Placed cards have a small × remove button that returns them to unplaced (Jessica). (5) Keyboard + screen-reader path: Tab/arrow nav, Space picks up, arrow keys cycle buckets, Space drops, Escape cancels; aria-live region announces transitions. Save payload reshaped — now has `not_interested` array in addition to `already_doing` / `willing_to_try` / `unplaced`. Export pipeline gains `sort_not_interested` (list) and `sort_n_not_interested` (count) columns. demoDataset distribution updated to ~25/25/15/35 (already/willing/not_interested/unplaced). Breaking change to save shape — demo-only, no real participant data exists yet.',
      '2026-05-11 · v2.0 — replaced all 7 skill labels with the kid-friendly Belonging Promoting Behaviors items from the locked pretest doc. Added tap-toggle "?" affordance on each card showing a 1–2 sentence definition (per Ginny, Stephanie, Holly). Unplaced layout switched from horizontal-wrap to vertical-stack to fit the longer sentence-style labels.',
      '2026-05-11 · v1.0 — initial demo release.',
    ],
  },
  'who-i-am-poem': {
    version: 'v3.1',
    updated: '2026-08-27',
    changelog: [
      '2026-08-27 · v3.1 — Draft 100 (MINOR — additive UX, no data-shape change). "See your poem" no longer just sits disabled when line 1 ("I am ___") is empty — it stays tappable, and tapping it while empty shows \'Please fill in the first line ("I am ___") before continuing.\' and scrolls to/highlights that line. The other 7 optional lines are unaffected — line 1 is the only required field. Save payload unchanged.',
      '2026-08-16 · v3.0 — Draft 88 Part B (MAJOR — a whole mid-flow screen is removed). The keepsake screen\'s "Save as image" button and the standalone poem SVG builder are removed; the on-screen poem card stays (the consolidated plan keepsake includes the poem lines). Nothing may invite the participant out of the app before the posttest: the program\'s only download actions now live on the post-posttest completion screen (DeliveryShellPage), which renders the consolidated Plan keepsake from the saved payloads. Response payload unchanged. (In the live flow the removed screen was never actually reached — the engine advances as soon as onSave resolves — so this mainly aligns the sandbox with the live experience.)',
      '2026-08-14 · v2.7 — Draft 71 C (MINOR — payload addition, fixes audit F3). Save payload gains `full_poem_text`: the assembled poem exactly as the keepsake screen renders it (reuses the existing buildPoemText helper, including the line-6/line-10 mirrors of line 1 and skipped empty optional lines). Individual field keys unchanged. Feeds the live outro\'s {{response.who_i_am_poem.full_poem_text}} pull-forward — which previously rendered an EMPTY keepsake box in production — and gives export an assembled-poem column option.',
      '2026-06-29 · v2.6 — Josh follow-up to v2.5. Removed the empty "I am ___" placeholder slots from the fill-in view entirely — from the participant\'s side, before the poem exists, the slots read as broken/confusing. Lines 6 and 10 still mirror line 1 on the finished keepsake card (buildPoemText), where the repetition is the payoff. Dropped the now-unused MirroredLine component. No data-shape change.',
      '2026-06-29 · v2.5 — Draft 36 Part B. During the fill-in view, lines 6 and 10 no longer echo line 1 as the kid types (Adrienne: the live repetition confused kids) — they now show an empty "I am ___" slot so the 10-line shape stays visible. The mirroring still renders on the finished keepsake card, where the repetition is the structural payoff. No data-shape change.',
      '2026-06-01 · v2.4 — Draft 20. Removed the visible line numbers (the small "1.", "2."… next to each input) and the "Line N — same as line 1" instructional caption that appeared next to the auto-mirrored lines 6 and 10 (Ginny\'s 2026-06-01 feedback — "having line 6 and line 10 written in like that might be confusing"). Lines 6 and 10 now render silently as the mirrored "I am ___" text. Poem structure, auto-mirroring logic, and keepsake output unchanged. No data-shape change.',
      '2026-05-13 · v2.3 — auto-titled the finished-poem card and keepsake-image PNG "Who I Am" (replacing "Your Poem"). Both surfaces match. Footer credit on the keepsake PNG unchanged. Per Stephanie 2026-05-15 + confirmed 2026-05-18 meeting.',
      '2026-05-12 · v2.2 — removed the worked example block that v2.0 added above the input form. Feedback was that the example was nudging kids toward mimicry. Activity now opens directly with the input form.',
      '2026-05-12 · v2.1 — keepsake screen gains a "Save as image" button. Builds a self-contained SVG of the poem (matches the on-screen amber card styling, with a small "SSI Platform · YYYY-MM-DD" footer credit) and rasterizes to PNG client-side. No data-shape change.',
      '2026-05-11 · v2.0 — rebuilt to Ginny\'s 10-line structure on a single screen (Poem structure.png). 8 kid inputs; lines 6 and 10 auto-mirror line 1. Worked example shown above the inputs (Holly). George Ella Lyon attribution removed (Ginny: "this isn\'t the Lyons format"). Save payload reshaped to 8 keys + saved_at — breaking change, demo-only.',
      '2026-05-11 · v1.0 — initial demo release.',
    ],
  },
  'letter-builder': {
    version: 'v3.1',
    updated: '2026-08-27',
    changelog: [
      '2026-08-27 · v3.1 — Draft 100 (MINOR — additive UX, no data-shape change). Save no longer just sits disabled when the letter is empty — it stays tappable, and tapping it while empty shows "Please write your letter before continuing." and scrolls to/highlights the textarea. Save payload unchanged.',
      '2026-08-16 · v3.0 — Draft 88 Part B (MAJOR — a whole mid-flow screen is removed). The done screen\'s "Save as image" button and the standalone letter SVG builder are removed; the letter still shows back in its keepsake card, with the save-or-print copy adjusted (the consolidated plan keepsake includes the letter as Words of Wisdom). Nothing may invite the participant out of the app before the posttest: the program\'s only download actions now live on the post-posttest completion screen (DeliveryShellPage), which renders the consolidated Plan keepsake from the saved payloads. Response payload unchanged. (In the live flow the removed screen was never actually reached — the engine advances as soon as onSave resolves — so this mainly aligns the sandbox with the live experience.)',
      '2026-06-18 · v2.3 — Draft 32 Part B. Closing message rewritten from the passive "That letter is yours." to "You can save or print this letter and look back on it whenever you need a reminder or some encouragement." (Holly). The done screen now also shows the letter back in a keepsake card and adds a "Save as image" button (reuses `downloadSvgStringAsPng`, same path as Who I Am Poem) so the "save" the copy references is a real affordance — the draft assumed a save button already existed; it did not, so it was added. No data-shape change.',
      '2026-06-08 · v2.2 — Draft 26. Added two optional scaffolding prompts (small italic list) under the main instruction: "What is one skill you would recommend?" and "What is one helpful thought you could share?" — seeds for kids who freeze on the blank textarea. No data-shape change.',
      '2026-05-13 · v2.1 — replaced context line above the textarea with Stephanie\'s reframe (2026-05-15, confirmed 2026-05-18 meeting): "What you would want to say to another teen who feels like they don\'t belong." Old wording ("Write a letter to another teen who is starting where you are now…") was too vague — recipient is now anchored in the same emotional state the kid is being asked to write to. Direct framing in the kid\'s own voice rather than instructional. No data-shape change.',
      '2026-05-11 · v2.0 — collapsed 6-section structured letter to a single free-write screen per Stephanie\'s 2026-05-11 feedback. Removed: click-to-add word-bank chips, cross-activity pull-forward from Getting Unstuck and Allies/Safety Net, keepsake-view step. Added a short context line and a one-sentence example (greyed/italic) outside the textarea. Save payload reshaped to { activity, letter, saved_at } — breaking change, demo-only.',
      '2026-05-11 · v1.0 — initial demo release.',
    ],
  },
  plan: {
    version: 'v5.2',
    updated: '2026-08-27',
    changelog: [
      '2026-08-27 · v5.2 — Draft 100 (MINOR — additive UX, no data-shape change) + Josh copy fix. Continue on the Skills to Try screen no longer just sits disabled when how/who/when are unfilled — it stays tappable, and tapping it while incomplete names which sub-field(s) are missing and scrolls to/highlights the first one; "pick a skill" and "fill in the sub-fields" are handled as the two distinct cases they are. Also: the 988 note on the plan keepsake (on-screen + PNG/PDF) now reads "If you ever feel very distressed..." instead of "If at any time during this program..." — the plan is read back well after the program ends — via a new `variant="plan"` on the shared CrisisLifelineNote; every other placement (Assent, Welcome, end-of-program) is unchanged. Save payload unchanged.',
      '2026-08-24 · v5.1 — Draft 96 (MINOR — additive UI, no data-shape change). New 988 Suicide & Crisis Lifeline callout (Dr. Sprang\'s ask, 2026-08-24 team meeting), always present at the end of both the on-screen PlanReview and the PNG/PDF keepsake (buildPlanKeepsakeSvg) — Sprang was explicit this should be part of what the kid keeps, not just shown once on-screen. Shares the same `CrisisLifelineNote` copy/component as the Assent screen and the end-of-program celebration screen. Draft copy, reviewable. Save payload unchanged.',
      '2026-08-16 · v5.0 — Draft 88 Part B (MAJOR — a whole mid-flow screen is removed). Screen 5\'s PNG/PDF download buttons are removed from the activity (copy now points to the end of the program); PlanReview / PlanDownloads / Keepsake / new buildSavedPlanModel are exported so the completion screen renders the same review + downloads from the saved payloads. Nothing may invite the participant out of the app before the posttest: the program\'s only download actions now live on the post-posttest completion screen (DeliveryShellPage), which renders the consolidated Plan keepsake from the saved payloads. Response payload unchanged. (In the live flow the removed screen was never actually reached — the engine advances as soon as onSave resolves — so this mainly aligns the sandbox with the live experience.)',
      '2026-08-15 · v4.0 — Draft 72 (MAJOR — the data source changes structurally; closes the flow-integration item deferred since Draft 21 / audit F1). The Plan now reads REAL cross-activity payloads in-session: new `src/lib/planRealData.js` maps the engine\'s token_key-keyed `sessionData` (belonging_skills_sort willing-to-try ids resolved through the shared skills set + per-skill how-examples for all 7; getting_unstuck worked thoughts incl. the v5.9 randomly-selected fallback pair, challenge → response, both_and → both_and_root + " AND " + statement; allies_safety_net kept allies post-Inspect + non-skipped Strengthen entries; letter_builder `letter`; who_i_am_poem `full_poem_text` (v2.7+; older payloads collapse the poem section); self_reflection inclusion memory) into the same planData contract v3.x rendered. `planDemoData.js` is now strictly the sandbox/IRB-preview fallback (caveat note shows only there). Empty states (Part C): empty willing-to-try bucket → the FULL skills list is offered with explaining copy (and the for-later/radar lists are suppressed rather than mislabeled); empty thoughts/letter/poem sections collapse cleanly from both the review and the PNG/PDF keepsake. `Plan` added to ACTIVITY_REGISTRY; live sec-10 placeholder swapped to custom_activity{Plan} in the builder tables (effective at the v6 republish). Save payload UNCHANGED (skill_commitment / inclusion_reflection). Mapper unit-tested against real captured live-session payloads (24 assertions incl. sparse/removed/skipped cases); TEMP unlisted QA surfaces at /demo/sandbox/plan-real-preview + plan-sparse-preview.',
      '2026-07-27 · v3.1 — Draft 55 Part C (2026-07-27 meeting). (1) Allies section typo "How could that be?" → "Who could that be?" (Jessica). (2) Dropped the additional Words of Wisdom writing prompt from the creation flow (Holly + Stephanie: the letter IS the words of wisdom) — creation flow 6 → 5 screens; the letter still surfaces in the final plan labeled "Words of Wisdom" (read-only); removed the `letter_reflection` payload key. (3) Skills to Try now enforces true pick-ONE: once a skill is picked the other willing-to-try skills lock ("for later") so the kid can\'t also fill them in; a "Pick a different skill" reset clears the selection. Save payload stays single `skill_commitment`. No structural change beyond the removed screen.',
      '2026-07-13 · v3.0 — 2026-07-13 meeting streamline (Draft 51). Skills to Try is now pick-one (participant chooses one willing-to-try skill to work through in detail; full list still surfaces on the final plan); Thoughts to Flip renamed to Thoughts to Practice and moved to plan-display only; Your People (Allies Strengthening pull-forward: per support type, the person who could strengthen it + one action) moved to plan-display only, replacing the pick-first-ally screen; Who You Are poem moved to plan-display only; When You Felt Included question reworded to "before, during, or after" with a new "Something else" (Other) option; Words of Wisdom instructional line moved to sit above the reflection input; PDF reworked to a single continuous page matching the PNG keepsake (rasterized from the same SVG); save/screenshot guidance added on the Saved screen. Screen count dropped 9 → 6. Save payload: skills_to_try[] → single skill_commitment; first_ally_outreach removed; inclusion_reflection gains other_used + other_text. Export: plan_skill_1..7_* + plan_first_ally/when replaced by plan_skill_pick_* (id/text/how/who/when); added plan_inclusion_behavior_other + _other_text.',
      '2026-07-10 · v2.0 — Round 7 (2026-07-07 meeting) restructure, Draft 43. Added per-skill "How could you demonstrate this skill?" required text input on Skills to try (with per-skill example placeholders; commitment = skill + how + who + when); renamed "Read your letter back" → "Words of Wisdom" per Sprang\'s aha reframe (screen heading, review-card label, PDF page, reflection prompt now "Any words of wisdom that stand out to you here?"); new Screen 7 surfacing the participant\'s Self-Reflection inclusion moment with a belonging-promoting-behaviors checklist (which behaviors they were already using; screen skipped when no inclusion text); safety qualifier text on all BPB surfaces per Sprang\'s dangerous-connection concern; read-only reminder of not-tried-yet BPBs on the review; PDF export grows to 6 pages with an inclusion-reflection page. Save payload grows: skills_to_try[].how + inclusion_reflection.behaviors_used[]. Export gains plan_skill_N_how + plan_inclusion_behavior_bsN columns. Now 9 screens. (Note: the BSS registry has 7 skills, bs1–bs7 — the draft\'s "8" references are corrected to 7 throughout.)',
      '2026-06-30 · v1.1 — Josh copy tweak. Screen 2 heading relabeled "Skills you said you\'d try." → "New Skills to Try". No data-shape change.',
      '2026-06-30 · v1.0 — Draft 39. Initial build of "Your Plan," the seventh Ready for Roots activity. 8-screen paginated flow: intro → skills to try (pulls Belonging Skills willing-to-try; kid picks who + when per skill) → thoughts to flip (read-only, from Getting Unstuck picks) → people in my corner (kept allies by type + Strengthen commitments; kid picks one ally + when to reach out first) → read your letter back (+ optional reflection) → who you are (full poem, read-only) → review → saved (PNG + jsPDF 5-page keepsake). Reads synthetic per-kid content from src/lib/planDemoData.js (real cross-activity pull-forward deferred per Draft 21). Save payload: { skills_to_try[], first_ally_outreach, letter_reflection, saved_at }. Replaces the /the-plan placeholder route (now redirects to /demo/sandbox/plan).',
    ],
  },
  posttest: {
    version: 'v1.1',
    updated: '2026-07-16',
    changelog: [
      '2026-07-16 · v1.1 — Jessica review note (6.29.26 doc). Program Feedback Acceptability scale: spelled out the value-2 anchor "Neither" → "Neither Agree nor Disagree" for clarity. No data-shape change.',
      '2026-05-13 · v1.0 — initial sandbox build of the locked Posttest survey (18 items: BHS, ASCS, NB, Belonging Worries, Perceived Helpfulness, Program Feedback Acceptability Likert + 2 open-response). 9-screen paginated flow mirroring the Pretest pattern. Shared survey-item components (SurveyItems.jsx). Save payload flat-keyed by `post_*` SPSS column names.',
    ],
  },
  followup: {
    version: 'v1.1',
    updated: '2026-06-08',
    changelog: [
      '2026-06-08 · v1.1 — Draft 26. Appraisals section scale shifted from 0-5 to 0-4 to match Getting Unstuck v5.4 (the two read the same shared `src/lib/appraisals.js` scale — anchors 0 Not At All True / 2 Somewhat True / 4 Definitely True). Item wording and order unchanged. fu_app_* value range narrows 0..5 → 0..4.',
      '2026-05-13 · v1.0 — initial sandbox build of the locked FollowUp Survey (30 items: BHS, ASCS, UCLA, NB, BPB, the 6 shared Appraisals items from `src/lib/appraisals.js`, Belonging Worries, permanency radio with Other-text, placement-disruption worry). 11-screen paginated flow mirroring the Pretest pattern. Save payload flat-keyed by `fu_*` SPSS column names.',
    ],
  },
  pretest: {
    version: 'v1.1',
    updated: '2026-07-16',
    changelog: [
      '2026-07-16 · v1.1 — Jessica review note (6.29.26 doc): added two items that were missing from the app. (1) Demographics gains an out-of-home-placements count ("How many out of home placements have you had?") as a required number field (payload key `placements`). (2) New 1-item "Placement Disruption Worry" scale on its own screen ("Your placement") between Belonging Worries and Program Expectation — "How worried are you right now that this placement will change?" on the locked 0–4 anchors (Not at all → Extremely), mirroring the FollowUp disruption item (payload key `pre_disruption_worry`). Now 11 screens. Production export columns for the two new items follow when they are added to the published survey snapshot in the builder (survey export is snapshot-driven, not from this sandbox file).',
      '2026-05-11 · v1.0 — initial sandbox build of the locked Belonging pretest (29 items: 6 demographics + 7 scales). 10-screen paginated flow mirroring the live session layout. Sliders require explicit interaction before counting as answered; pre_bw_2 hidden when pre_bw_1 = 0. Save payload keyed by SPSS column names from Draft 6.',
    ],
  },
  demographics: {
    version: 'v1.1',
    updated: '2026-08-27',
    changelog: [
      '2026-08-27 · v1.1 — Draft 100 (MINOR — additive UX, no data-shape change). Continue no longer just sits disabled when a field is missing — it stays tappable, and tapping it while incomplete names which field is missing (or, with several missing, highlights and scrolls to the first) instead of leaving the kid to hunt for it. Save payload unchanged.',
      "2026-08-26 · v1.0 — new: demographics + Placement Disruption Worry items added to fill a gap between the live pretest and the polished /demo Pretest.jsx reference (age/sex/race/hispanic/grade/home time/placements; disruption-worry Likert item as a separate component, see 'placement-disruption-worry').",
    ],
  },
  'placement-disruption-worry': {
    version: 'v1.0',
    updated: '2026-08-26',
    changelog: [
      "2026-08-26 · v1.0 — new: demographics + Placement Disruption Worry items added to fill a gap between the live pretest and the polished /demo Pretest.jsx reference (age/sex/race/hispanic/grade/home time/placements as a separate component, see 'demographics'; this component is the disruption-worry Likert item).",
    ],
  },
}

// Convenience lookup. Returns null if the id isn't registered (e.g. for
// feedback submitted from the demo home page).
export function getActivityVersion(id) {
  if (!id) return null
  return ACTIVITY_VERSIONS[id] || null
}
